# Generated by Django 4.2.4 on 2023-09-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_condicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicion',
            name='condicioin',
        ),
        migrations.AddField(
            model_name='condicion',
            name='condicion',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.condicion'),
        ),
    ]
