# Generated by Django 4.2.4 on 2023-09-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_usuario_condicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='condicion',
            new_name='padecimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='recomendaciones_condicion',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='condicion',
            field=models.CharField(max_length=20),
        ),
    ]
