# Generated by Django 4.2.4 on 2023-09-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('alergias', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('num_contact', models.IntegerField()),
            ],
        ),
    ]
