# Generated by Django 4.2.4 on 2023-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usuario_condicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicioin', models.CharField(max_length=20)),
                ('recomendacion', models.TextField()),
            ],
        ),
    ]
