# Generated by Django 4.2.4 on 2023-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_condicion_condicioin_condicion_condicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='condicion',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
