# Generated by Django 4.2.5 on 2023-09-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_condicion_usuario_padecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='recomendaciones_condicion',
        ),
    ]
