# Generated by Django 4.2.5 on 2023-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_usuario_recomendaciones_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recomendaciones_condicion',
            field=models.TextField(default='No se encontraron recomendaciones para esta condición'),
        ),
    ]
